<MemoryScreen>
    Label:
        text: "Memory Game"
        font_size: 50
        size_hint: 1, 0.1
        pos_hint: {"top": 1}
        color: 0, 0, 0, 1
    Label:
        text: "Score: " + str(root.score)
        font_size: 30
        size_hint: 1, 0.1
        pos_hint: {"top": 0.9, "center_x": 0.5}
        color: 0, 0, 0, 1
    MDGridLayout:
        id: grid
        size_hint: None, None
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        height: root.height - 100
        width: root.width
        cols: 3
        rows: 5
        padding: "10dp"
        spacing: "10dp"

<MemoryCard>
    padding: "10dp"
    size_hint: 0.33, 0.25
    MDRelativeLayout:
        Button:
            id: img
            opacity: 0
            fit_mode: "contain"
            background_normal: "test.png"
            background_disabled_normal: "test.png"
            on_press: root.button_click()
            disabled: False




