
<Carousel>:
    AsyncImage:
        source: '/Finger-Sign-BSL/a.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/b.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/c.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/d.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/e.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/f.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/g.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/h.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/i.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/j.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/k.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/l.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/m.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/n.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/o.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/p.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/q.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/r.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/s.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/t.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/u.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/v.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/w.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/x.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/y.jpg'
    AsyncImage:
        source: '/Finger-Sign-BSL/z.jpg'
