<MemoryScreen>
    MDGridLayout:
        id: grid
        size_hint: None, None
        height: root.height
        width: root.width
        cols: 3
        rows: 4
        padding: "10dp"
        spacing: "10dp"

<MemoryCard>
    padding: "10dp"
    size_hint: 0.33, 0.25
    MDRelativeLayout:
        Button:
            id: img
            opacity: 0
            fit_mode: "contain"
            background_normal: "test.png"
            on_press: root.button_test()




